### PR TITLE
Fix: Tdi SPREAD function does not work on scalars

### LINKED ISSUE #2503: TDI function "spread()" crashes if called with a scalar argument
Hi,
I just noticed that spread() now crashes if the first argument is a scalar:

$ tdic
TDI> spread(2.5,0,10)
malloc(): invalid size (unsorted)
Abort (core dumped)
$ 

Passing a one-element array works. 

I am using mdsplus-alpha 7.139.12 on Ubuntu 20.04
$ uname -a
Linux xxx 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Greetings,
Wolfgang

### PR DESCRIPTION
**Pull request by joshStillerman**
The TDI SPREAD and REPLICATE functions were treating the pointer 'pa'
as an array descriptor, while it was copied from a scalar descriptor.

Instead just copy the first sizeof(struct descriptor) bytes, and at
the bottom of Tdi1Trans Build the array descriptor that we want.

Closes: https://github.com/MDSplus/mdsplus/issues/2503

### CODE REVIEW

File: tdishr/TdiTrans.c [hunk 1]
```diff
@@ -291,8 +291,15 @@ int Tdi1Trans(int opcode, int narg, mdsdsc_t *list[], mdsdsc_xd_t *out_ptr)
...
     /** scalar to simple vector **/
-    if (rank == 0)
-      memcpy((char *)&arr, (char *)pa, head);
+    if (rank == 0) {
+      memcpy((char *)&arr, (char *)pa, sizeof(struct descriptor));
+      arr.dimct = 1;
+      arr.aflags.coeff = 0;
+      arr.a0 = arr.pointer;
+      arr.arsize = arr.length;
+      arr.m[1] = arr.m[0] = 1;
```
Comment (WhoBrokeTheBuild) [inline tdishr/TdiTrans.c]: Style-wise, we should avoid multiple assignments on a single line, it can get hard to read.

**Review by WhoBrokeTheBuild — DISMISSED** [review]

**Comment by joshStillerman** [comment]
retest this please

**Review by WhoBrokeTheBuild — APPROVED** [review]
