### PR TITLE
Fix: 2625 v2 - only change IDL for socket 0 issue

### LINKED ISSUE #2625: IDL - mdsisclient can't check against socket=0 causing further issues when set_database claims !mdsdb_socket=0
**Affiliation**

DIII-D

-----

**Version(s) Affected**

Current / Alpha Branch

-----

**Platform**

Linux (RHEL8), IDL API (original bug), Python API (introduced bug)

-----

**Describe the bug**

If `set_database` is called with the intention to proxy through a mdshost, then multiple issues occur if `set_database` receives the first socket id inside the IDL session (i.e. `!MDSDB_SOCKET=0`).

This appears to occur because:
- MDSplus sockets allow for a socket id=0.
- Multiple IDL functions use `mdsisclient` to check a socket passed via keyword.
- The `mdsisclient` function then relies on `keyword_set(socket)`.
- The IDL `keyword_set` function returns `false` if defined and the value is zero.
- The `mdsisclient` function does fall through when `keyword_set(socket)` returns `false`, but... only checks against `!MDS_SOCKET`.

Thus weird failure states happen when `set_database` claims socket id=0, resulting in `mdsisclient` being unable to confirm the socket via `keyword_set`, and then ultimately `dsql` and `mdsvalue` don't know how and/or where to execute SQL calls through TDI.

-----

**Examples**

Note that my .sybase_login file for these examples define the mdshost='atlas-el8.gat.com', so we know whether a successful dsql call gets evaluated via the intended proxy (i.e. atlas-el8,gat.com), or via localhost (i.e. omega01.gat.com), or not at all.

1) The mdsip connection to the mdshost gets opened but the dsql still executes from the localhost:
```
[flanagan@omega01 ~]$ idl
IDL> set_database,'d3drdb'
IDL> help,!MDS_SOCKET,!MDSDB_SOCKET
<Expression>    INT       =       -1
<Expression>    INT       =        0
IDL> n = dsql('select host_name()',val) & print,val
omega01.gat.com
```

2) A subsequent mdsconnect to any server will prevent dsql from being able to execute:
```
[flanagan@omega01 ~]$ idl
IDL> set_database,'d3drdb'
IDL> mdsconnect,'atlas.gat.com'
IDL> help,!MDS_SOCKET,!MDSDB_SOCKET
<Expression>    INT       =        1
<Expression>    INT       =        0
IDL> n = dsql('select host_name()',val) & print,val
% DSQL: SET_DATABASE must preceed any DSQL calls
% PRINT: Variable is undefined: VAL.
% Execution halted at: $MAIN$
```

3) Until another set_database call claims a different non-zero socket id:
```
[flanagan@omega01 ~]$ idl
IDL> set_database,'d3drdb'
IDL> mdsconnect,'atlas.gat.com'
IDL> set_database,'d3drdb'
IDL> help,!MDS_SOCKET,!MDSDB_SOCKET
<Expression>    INT       =        1
<Expression>    INT       =        2
IDL> n = dsql('select host_name()',val) & print,val
atlas-el8.gat.com
```

-----

**Discussion**

I tried fixing the logic in mdsisclient but it exposed other technical debt that I'm not eager to delve into.  

Instead, I'm wondering if this scenario can be triaged by disallowing mdsplus sockets with id=0?  

Would starting at socket id=1 be a simpler solution?

-----

### PR DESCRIPTION
**Pull request by mwinkel-dev**
Replaces PR #2626 which did not work at sites that have a mixture of old and new software on their servers.

This version changes the IDL code so that zero is accepted as a valid connection ID.

### CODE REVIEW

File: mdstcpip/mdsipshr/Connections.c [hunk 1]
```diff
@@ -471,7 +471,7 @@ int AddConnection(Connection *c)
   do
   {
     id++; // find next free id
-  } while (id == INVALID_CONNECTION_ID && _FindConnection(id, NULL, MDSIPTHREADSTATIC_VAR));
+  } while ((id == INVALID_CONNECTION_ID) || _FindConnection(id, NULL, MDSIPTHREADSTATIC_VAR));
```
Comment (WhoBrokeTheBuild) [inline mdstcpip/mdsipshr/Connections.c:474]: Just for tracking, this is fixed re: Timo's comments:
https://github.com/MDSplus/mdsplus/pull/2626#discussion_r1338879619

**Review by WhoBrokeTheBuild — APPROVED** [review]
