### PR TITLE
Fix: null terminate truncated node names (2472)

### LINKED ISSUE #2472: MDSplus8: -- inconsistent max node name length
Using the old-trees branch, create a new tree.   Using TCL, attempt to add a 70 character node name.   Dir command shows it was truncated to 63 characters.  Now open the same tree in jTraverser -- it shows 64 characters.   However jTraverser2 only shows 63 characters.

In the underlying data structures, is the node name a 65 character field (64 visible characters + 1 null terminator)?   Or is it a 64 character field (63 visible characters + 1 null terminator)?   Behavior demonstrated by this bug indicates inconsistent definition of the maximum node length.

old_trees_char64_bug

### PR DESCRIPTION
**Pull request by mwinkel-dev**
Fixes issue with mdsplus8 not properly truncating node names longer than 63 visible characters.

### CODE REVIEW

File: treeshr/TreeAddNode.c [hunk 1]
```diff
@@ -160,6 +160,7 @@ int _TreeAddNode(void *dbid, char const *name, int *nid_out, char usage)
 #pragma GCC diagnostic pop
           for (i = strlen(node_name); i < sizeof(new_ptr->name); i++)
             new_ptr->name[i] = 0;
+          new_ptr->name[MAX_NAME_LEN] = 0;  // null terminate truncated names
```
Comment (WhoBrokeTheBuild) [inline treeshr/TreeAddNode.c]: When adding a null terminator to a string we prefer to use '\0'  instead, helps convey the intent. If you add that, you can drop the comment, it will be conveyed by the code

File: treeshr/TreeRenameNode.c [hunk 2]
```diff
@@ -210,10 +210,16 @@ int _TreeRenameNode(void *dbid, int nid, char const *newname)
...
+  // Set name with logic similar to _TreeAddNode()
+#pragma GCC diagnostic push
+#if defined __GNUC__ && 800 <= __GNUC__ * 100 + __GNUC_MINOR__
+  _Pragma("GCC diagnostic ignored \"-Wstringop-truncation\"")
+#endif
+  strncpy(oldnode_ptr->name, newnode_name, sizeof(oldnode_ptr->name));
+#pragma GCC diagnostic pop
+  for (i = strlen(newnode_name); i < (int) sizeof(oldnode_ptr->name); i++)
+    oldnode_ptr->name[i] = 0;
+  oldnode_ptr->name[MAX_NAME_LEN] = 0;  // null terminate truncated names
```
Comment (WhoBrokeTheBuild) [inline treeshr/TreeRenameNode.c]: Same comment as above

**Review by WhoBrokeTheBuild — CHANGES_REQUESTED** [review]

File: treeshr/TreeAddNode.c (hunk 1 above)
Comment (mwinkel-dev) [reply treeshr/TreeAddNode.c]: Agreed.

File: treeshr/TreeRenameNode.c (hunk 2 above)
Comment (mwinkel-dev) [reply treeshr/TreeRenameNode.c]: Agreed.

**Comment by mwinkel-dev** [comment]
Requested changes made and tested on Ubuntu 22.

**Review by WhoBrokeTheBuild — APPROVED** [review]

**Comment by mwinkel-dev** [comment]
On 20-Apr-2023, manual testing done after the PR was merged confirmed that the fix works.
