### PR TITLE
Fix: fix brother of subtree nodes.

### LINKED ISSUE #2972: Issues with release build and brother_of (and similar) functions
**Affiliation**
MIT PSFC

**Version(s) Affected**
Alpha 7.154.0

**Platform(s)**
Ubuntu 24.04, others

**Installation Method(s)**
mdsplus.org repository

**Describe the bug**
There are issues with brother_of and other similar functions being optimized to the point of breaking.

This might be affecting nodes that come after subtree nodes, or specifically subtree nodes that follow other subtree nodes, it's difficult to say.

**To Reproduce**
0. Run a release build, from the packages or `-DCMAKE_BUILD_TYPE=Release` or `RelWithDebInfo`
1. `tdic`
2. `treeopen('cmod', 1090909009)`
3. `getnci(\top, 'children_nids')`

**Expected behavior**
Expect to see a long list of nodes, see only 2

### PR DESCRIPTION
**Pull request by joshStillerman**
The optimizer is deciding that it does not need to fill in the brother nid of nodes that are subtree attachment points. Making the variable that holds it volatile forces the optimizer to do the right thing.

Fixes: https://github.com/MDSplus/mdsplus/issues/2972

### CODE REVIEW

**Review by WhoBrokeTheBuild — APPROVED** [review]
What a wild ride to find this, good work and let's hope there aren't any other bugs like this around

File: treeshr/TreeOpen.c [hunk 1]
```diff
@@ -1174,17 +1174,23 @@ static int GetVmForTree(TREE_INFO *info, int nomap)
 static void SubtreeNodeConnect(PINO_DATABASE *dblist, NODE *parent,
                                NODE *subtreetop)
 {
-  NID child_nid, parent_nid, brother_nid = {0, 0};
+  NID child_nid, parent_nid = {0, 0};
```
Comment (WhoBrokeTheBuild) [inline treeshr/TreeOpen.c:1177]: One note here, is that the old line reads like all things are getting assigned a default, but only `brother_nid` was. So this is now changing it to give a default to `parent_nid` as well. This shouldn't be an issue, but is a change.

**Review by heidthecamp — APPROVED** [review]
