### PR TITLE
Fix: Handling of segments which have expression dim

### LINKED ISSUE #1291: Possible bug with makesegment or compile using Python 3.6.5 and MDSplus alpha 7.40.0
Dear all,

my test program shows problematic error with what I call case "D". The program just takes note of the time required to perform data upload and download in a variety of cases (different ways to store signals). The program can upload and download both using the distributed client and the thin client. I used to test it both locally and using a remote server.

I think I have isolated the problem. The following code
```
timebase = Int64Array(range(100))*10
signal = Int16Array(range(100))*-1

tree = Tree("localtest", 99, "NEW")
timeNode = tree.addNode("TIME", "SIGNAL")
dataNode = tree.addNode("DATA", "SIGNAL")
tree.write()

timeNode.makeSegment(timebase[0], timebase[-1], timebase, timebase)
tmp = Data.compile('quadword(getsegment(TIME, 0))')           
dataNode.makeSegment(timebase[0], timebase[-1], tmp, Int16Array(signal))

readTimebase = timeNode.getData().data()
readData = dataNode.getData().data()

tree.close()
```
gives this error when data is accessed:

```
Traceback (most recent call last):

  File "<ipython-input-1-53c2c0e15447>", line 16, in <module>
    readData = dataNode.getData().data()

  File "C:\Anaconda3\lib\site-packages\mdsplus-7.7.5-py3.6.egg\MDSplus\tree.py", line 1645, in getRecord
    raise _exc.MDSplusException(status)

LibKEYNOTFOU: %LIB-F-KEYNOTFOU, Key not found
```

Also, if I use the distributed client to read the data
```
conn = Connection("127.0.0.1")
conn.openTree("localtest", 99)

readTimebase = conn.get("TIME")
readData = conn.get("DATA")

conn.closeTree("localtest", 99)
```
I get the same error.
```
Traceback (most recent call last):

  File "<ipython-input-2-30cdb0ebced9>", line 5, in <module>
    readData = conn.get("DATA")

  File "C:\Anaconda3\lib\site-packages\mdsplus-7.7.5-py3.6.egg\MDSplus\connection.py", line 213, in get
    return self.__getAnswer__()

  File "C:\Anaconda3\lib\site-packages\mdsplus-7.7.5-py3.6.egg\MDSplus\connection.py", line 81, in __getAnswer__
    _exc.checkStatus(_GetAnswerInfoTS(self.socket,dtype,length,ndims,dims.ctypes.data,numbytes,_C.byref(ans),_C.byref(mem)))

  File "C:\Anaconda3\lib\site-packages\mdsplus-7.7.5-py3.6.egg\MDSplus\mdsExceptions.py", line 60, in checkStatus
    raise MDSplusException(status)

LibKEYNOTFOU: %LIB-F-KEYNOTFOU, Key not found
```

Strangely enough, if I then use the thin client for the upload:
```
tree = Tree("localtest", 98, "NEW")
timeNode = tree.addNode("TIME", "SIGNAL")
dataNode = tree.addNode("DATA", "SIGNAL")
tree.write()
tree.close()

conn = Connection("127.0.0.1")
conn.openTree("localtest", 98)

conn.get('MakeSegment(TIME, $1, $2, $3, $4, , 100)', timebase[0], timebase[-1], timebase, timebase)
conn.get('MakeSegment(DATA, $1, $2, Compile("quadword(getsegment(TIME, 0)"), $3, , 100)', Int64(timebase[0]), Int64(timebase[-1]), Int16Array(signal))

readTimebase = conn.get("TIME")
readData = conn.get("DATA")

conn.closeTree("localtest", 98)
```
I get the error:
```
Traceback (most recent call last):

  File "<ipython-input-3-1169cd2ef40b>", line 14, in <module>
    readData = conn.get("DATA")

  File "C:\Anaconda3\lib\site-packages\mdsplus-7.7.5-py3.6.egg\MDSplus\connection.py", line 213, in get
    return self.__getAnswer__()

  File "C:\Anaconda3\lib\site-packages\mdsplus-7.7.5-py3.6.egg\MDSplus\connection.py", line 81, in __getAnswer__
    _exc.checkStatus(_GetAnswerInfoTS(self.socket,dtype,length,ndims,dims.ctypes.data,numbytes,_C.byref(ans),_C.byref(mem)))

  File "C:\Anaconda3\lib\site-packages\mdsplus-7.7.5-py3.6.egg\MDSplus\mdsExceptions.py", line 60, in checkStatus
    raise MDSplusException(status)

TdiSYNTAX: %TDI-E-SYNTAX, Bad punctuation or misspelt word or number
```
and finally, if I then try to read the data uploaded with the thin client using the distributed client
```
tree = Tree("localtest", 98)
timeNode = tree.getNode("TIME")
dataNode = tree.getNode("DATA")

readTimebase = timeNode.getData().data()
readData = dataNode.getData().data()

tree.close()
```
The python kernel dies executing the instructions at the readData line.

Note that with MDSplus version 7.7.12, without changing anything in the code, using the distributed client for reading still crashed the Python kernel, but the thin client read was successful.

Referring to issue #1290, it seems that the method Tree.close() is present in my installation and the indexing with negative values also seems working correctly.

In case of need, I included the whole files I use for testing (one defining a class, the other an example of its use). [Test MDSplus.zip](https://github.com/MDSplus/mdsplus/files/1933973/Test.MDSplus.zip)

Sincerely,

### PR DESCRIPTION
**Pull request by tfredian**
The attempt to store segments which contain expressions for
the dimension of a segment uncovered problems in the handling
of segments. The existing code assumed that the dimensions of
segments were either ranges or arrays when combining multiple
segments into a single signal. This PR should fix some of the problems.
There is still further work needed to either support other such
features and/or restrict what can be stored in a segment to
prevent unexpected behaviors.

This should fix https://github.com/MDSplus/mdsplus/issues/1291

### CODE REVIEW

File: xtreeshr/XTreeGetTimedRecord.c [hunk 1]
```diff
@@ -312,6 +312,12 @@ EXPORT int _XTreeGetTimedRecord(void *dbid, int inNid, struct descriptor *startD
 		status = (dbid)?_TreeGetSegment(dbid, nid, currIdx, &dataXds[currSegIdx], &dimensionXds[currSegIdx]):TreeGetSegment(nid, currIdx, &dataXds[currSegIdx], &dimensionXds[currSegIdx]);
 
 //printf("Read Segment %d\n", currSegIdx);
+		if STATUS_OK
+		{
+		  if (dimensionXds[currSegIdx].pointer->dtype == DTYPE_FUNCTION) {
+		    status = TdiData(dimensionXds[currSegIdx].pointer,&dimensionXds[currSegIdx] MDS_END_ARG);
```
Comment (zack-vii) [inline xtreeshr/XTreeGetTimedRecord.c]: i would not check for FUNCTION but for the class.
or call data in any case which could be a NOP if the argument is already a simple type (array or scalar)

**Review by zack-vii — CHANGES_REQUESTED** [review]
the handling in XTreeGetTimedRecord needs improvement

File: xtreeshr/XTreeGetTimedRecord.c (hunk 1 above)
Comment (tfredian) [reply xtreeshr/XTreeGetTimedRecord.c]: I changed it to always do TdiData() for the dim.

**Review by zack-vii — APPROVED** [review]
